name: Auto commit

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 7,0,11,18 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          cat > LAST_UPDATED
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "rafli.rfsp@gmail.com"
          git config --local user.name "rsurya99"
          git add -A
          git commit -m "There's nothing in here"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
